# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Terry Roberts
email: roberts.terry@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Web Developer - Software Engineer - User Experience Designer
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://tezbo.github.com" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
twitter_username: terrytiger
github_username:  tezbo
#instagram_username: beyonce
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123
#linkedin_url: https://

# Address information
address_street: 8 Nicholson St
address_city: Melbourne
address_state: VIC
address_zip: 3000

# Build settings
markdown: kramdown
